// Maps every real FBS school (as named in the game's Team table) to its actual
// home state. Hardcoded from real-world knowledge rather than parsed from the
// save file, since the save doesn't expose a usable state field on teams and
// these are all real, well-known university locations.
const TEAM_STATE_BY_NAME = {
    'Air Force': 'Colorado',
    'Akron': 'Ohio',
    'Alabama': 'Alabama',
    'App St.': 'North Carolina',
    'Arizona': 'Arizona',
    'Arizona State': 'Arizona',
    'Arkansas': 'Arkansas',
    'Arkansas State': 'Arkansas',
    'Army': 'New York',
    'Auburn': 'Alabama',
    'Ball State': 'Indiana',
    'Baylor': 'Texas',
    'Boise State': 'Idaho',
    'Boston College': 'Massachusetts',
    'Bowling Green': 'Ohio',
    'Buffalo': 'New York',
    'BYU': 'Utah',
    'C. Carolina': 'South Carolina',
    'C. Michigan': 'Michigan',
    'California': 'California',
    'Charlotte': 'North Carolina',
    'Cincinnati': 'Ohio',
    'Clemson': 'South Carolina',
    'Colorado': 'Colorado',
    'Colorado State': 'Colorado',
    'Delaware': 'Delaware',
    'Duke': 'North Carolina',
    'E. Michigan': 'Michigan',
    'East Carolina': 'North Carolina',
    'FIU': 'Florida',
    'FLA Atlantic': 'Florida',
    'Florida': 'Florida',
    'Florida State': 'Florida',
    'Fresno State': 'California',
    'Ga Southern': 'Georgia',
    'Georgia': 'Georgia',
    'Georgia State': 'Georgia',
    'Georgia Tech': 'Georgia',
    "Hawai'i": 'Hawaii',
    'Houston': 'Texas',
    'Illinois': 'Illinois',
    'Indiana': 'Indiana',
    'Iowa': 'Iowa',
    'Iowa State': 'Iowa',
    'James Madison': 'Virginia',
    'Jax State': 'Alabama',
    'Kansas': 'Kansas',
    'Kansas State': 'Kansas',
    'Kennesaw St.': 'Georgia',
    'Kent State': 'Ohio',
    'Kentucky': 'Kentucky',
    'Liberty': 'Virginia',
    'Louisiana': 'Louisiana',
    'Louisiana Tech': 'Louisiana',
    'Louisville': 'Kentucky',
    'LSU': 'Louisiana',
    'Marshall': 'West Virginia',
    'Maryland': 'Maryland',
    'Memphis': 'Tennessee',
    'Miami': 'Florida',
    'Miami (OH)': 'Ohio',
    'Michigan': 'Michigan',
    'Michigan State': 'Michigan',
    'Minnesota': 'Minnesota',
    'Mississippi St': 'Mississippi',
    'Missouri': 'Missouri',
    'Missouri State': 'Missouri',
    'MTSU': 'Tennessee',
    'Navy': 'Maryland',
    'NC State': 'North Carolina',
    'NDSU': 'North Dakota',
    'Nebraska': 'Nebraska',
    'Nevada': 'Nevada',
    'New Mexico': 'New Mexico',
    'New Mexico St.': 'New Mexico',
    'NIU': 'Illinois',
    'North Carolina': 'North Carolina',
    'North Texas': 'Texas',
    'Northwestern': 'Illinois',
    'Notre Dame': 'Indiana',
    'Ohio': 'Ohio',
    'Ohio State': 'Ohio',
    'Oklahoma': 'Oklahoma',
    'Oklahoma State': 'Oklahoma',
    'Old Dominion': 'Virginia',
    'Ole Miss': 'Mississippi',
    'Oregon': 'Oregon',
    'Oregon State': 'Oregon',
    'Penn State': 'Pennsylvania',
    'Pittsburgh': 'Pennsylvania',
    'Purdue': 'Indiana',
    'Rice': 'Texas',
    'Rutgers': 'New Jersey',
    'Sac State': 'California',
    'Sam Houston': 'Texas',
    'San Diego St.': 'California',
    'San Jose State': 'California',
    'SMU': 'Texas',
    'South Alabama': 'Alabama',
    'South Carolina': 'South Carolina',
    'Southern Miss': 'Mississippi',
    'Stanford': 'California',
    'Syracuse': 'New York',
    'TCU': 'Texas',
    'Temple': 'Pennsylvania',
    'Tennessee': 'Tennessee',
    'Texas': 'Texas',
    'Texas A&M': 'Texas',
    'Texas State': 'Texas',
    'Texas Tech': 'Texas',
    'Toledo': 'Ohio',
    'Troy': 'Alabama',
    'Tulane': 'Louisiana',
    'Tulsa': 'Oklahoma',
    'UAB': 'Alabama',
    'UCF': 'Florida',
    'UCLA': 'California',
    'UConn': 'Connecticut',
    'UL Monroe': 'Louisiana',
    'UMass': 'Massachusetts',
    'UNLV': 'Nevada',
    'USC': 'California',
    'USF': 'Florida',
    'Utah': 'Utah',
    'Utah State': 'Utah',
    'UTEP': 'Texas',
    'UTSA': 'Texas',
    'Vanderbilt': 'Tennessee',
    'Virginia': 'Virginia',
    'Virginia Tech': 'Virginia',
    'W. Kentucky': 'Kentucky',
    'W. Michigan': 'Michigan',
    'Wake Forest': 'North Carolina',
    'Washington': 'Washington',
    'Washington St.': 'Washington',
    'West Virginia': 'West Virginia',
    'Wisconsin': 'Wisconsin',
    'Wyoming': 'Wyoming'
};

module.exports = { TEAM_STATE_BY_NAME };
